import { Work_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "./_utility/Navbar";
import Footer from "./_utility/Footer";
import ThemeContextProvider from "./context/ThemeContext";

const WorkSans = Work_Sans({ subsets: ["latin"], weights: ["400", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className=" overflow-x-hidden" lang="en">
      <body className={`${WorkSans.className}  dark:bg-black  bg-white`}>
        <ThemeContextProvider>
          <Navbar />
          {children}
          <Footer />
        </ThemeContextProvider>
      </body>
    </html>
  );
}
